import Header from "./Header/Header"
import Footer from "./Footer/Footer"
import Head from 'next/head'
import FooterMobile from "./Footer/FooterMobile"


export default function Layout({ children }) {

    return (
        <div className="min-h-screen	flex flex-col">  
            <Head>
                <title></title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="../public/favicon.ico" />
            </Head>
          
                <Header />
                <main  className="flex-grow">{children}</main>
                <Footer />
                <FooterMobile/>
      </div>
      
    )
  }