import Header from "./Header/Header"
import Footer from "./Footer/Footer"
import Head from 'next/head'
import FooterMobile from "./Footer/FooterMobile"


export default function Layout({ children }) {

    return (
        <div className="h-full">  
            <Head>
                <title></title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="../public/favicon.ico" />
            </Head>
            <div className="relative h-screen"             style={{marginBottom: '-5rem'}}
>
                <Header />
                <main >{children}</main>
                <Footer />
                <FooterMobile/>
            </div>
      </div>
      
    )
  }