import React from 'react'
import Head from 'next/head'


const about = () => {
    return (
        <>
            <Head>
                <title>Brews With Brule</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <article className='flex flex-col pt-12 relative mb-12'>
                    <div className='px-6'>
                        <h2 className='text-1.5 italic mb-3'>About us</h2>
                        <p className='text-0.875 mb-6'>Welcome to Brews With Brule! We're all about friends getting together to enjoy a cold one and have a good time. At our core, we believe in the power of friendship and the role that beer plays in bringing people together.
                        </p>
                        <a href="#team"><button className='bg-dark text-white w-full h-12'>Meet the team</button></a>
                    </div>
                    <img className='hidden relative pt-8 w-60' src='https://plus.unsplash.com/premium_photo-1658526884541-e74c95642c6d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1172&q=80' />
                </article>
                <article className='flex flex-col relative mb-12'>
                    <div className='px-6'>
                        <h2 className='text-1.5 italic mb-3 text-primary'>A hub for beer enthusiasts</h2>
                        <p className='text-0.875 mb-6'>
                            Our website is a place for beer enthusiasts of all levels to come and learn more about the world of beer. From reviews of new and exciting brews, to tips and tricks for hosting the perfect beer tasting party with friends, we've got you covered.
                        </p>
                        <button className='bg-primary text-white w-full h-12'>Our favorite breweries</button>
                    </div>
                </article>
                <article className='flex flex-col relative mb-12'>
                    <div className='px-6'>
                        <h2 className='text-1.5 italic mb-3 '>A community for beer lovers to share their passion.</h2>
                        <p className='text-0.875 mb-6'>
                            We're dedicated to providing a fun and welcoming space for all beer lovers to come and share their passion. So grab a cold one and join us on our journey of discovery through the world of beer and friendship.

                        </p>
                        <button className='bg-dark text-white w-full h-12'>Join us today!</button>
                    </div>
                </article>

            </main>
        </>

    )
}

export default about