import React from 'react'
import Head from 'next/head'


const post = () => {
    return (
        <>
            <Head>
                <title>Brews With Brule</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className='flex flex-col items-center'>
                    <h2 className='font-semibold text-1.5'>Create a post</h2>
                    <form className='w-full px-6'>
                        <div className='flex items-left flex-col mb-8 w-full lg:w-80'>
                            <div className='flex justify-between items-center w-full mb-1'>
                                <label className='font-semibold text-0.875 '>Title</label>
                                <p className='text-0.875 text-medium italic'>40/40 remaining</p>
                            </div>
                            <input className='rounded-lg h-12 p-4 font-semibold text-0.875 border-solid border-light border-2' name='username' type='text'></input>
                        </div>
                    </form>
                </div>
            </main>
        </>
    )
}

export default post