import React from 'react'
import Head from 'next/head'
import PostForm from '@/components/Post/PostForm'


const post = () => {

    return (
        <>
            <Head>
                <title>Brews With Brule</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className='flex flex-col items-center justify-center pt-12'>
                    <h2 className='font-semibold text-1.5 mb-8 lg:mb-4'>Create a post</h2>
                    <PostForm />
                </div>
            </main>
        </>
    )
}

export default post