import BreweryCTA from '@/components/Breweries/BreweryCTA'
import BreweryData from '@/components/Breweries/BreweryData'
import BreweryImage from '@/components/Breweries/BreweryImage'
import BreweryList from '@/components/Breweries/BreweryList'
import BreweryMap from '@/components/Breweries/BreweryMap'
import BreweryName from '@/components/Breweries/BreweryName'
import Header from '@/components/Header/Header'
import Head from 'next/head'
import React from 'react'
import {useRouter} from 'next/router'

const breweries = ({url}) => {
    const router = useRouter().query.pid
    console.log(router)
    return (
        <>
            <Head>
                <title></title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <section className='flex flex-col justify-center items-center w-full'>
                <BreweryImage />
                <section className='xl:flex xl:justify-around xl:w-70'>
                    <article className=' flex flex-col '>
                        <BreweryName />
                        <BreweryData />
                        <BreweryCTA />
                    </article>
                    <BreweryMap />
                </section>
                <BreweryList />
            </section></>

    )
}

export default breweries